version: '3'

services:
  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - "0.0.0.0:8080:80"
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
    links:
      - registry:registry

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - ./registry:/var/lib/registry
      - ./registry/data:/tmp/registry
