version: '3'

services:
  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - "0.0.0.0:4444:80"
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
    links:
      - registry:registry

  registry:
    image: registry:2.3.0
    ports:
      - "5000:5000"
    volumes:
      - ./registry:/var/lib/registry
